version: "3.9"

services:
  backend:
    container_name: backend-container
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./backend/.env  # Load environment variables from .env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env  # Load environment variables from .env
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    container_name: db-container
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data across restarts
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # Mount init.sql to auto-execute

volumes:
  pgdata: