name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  ci:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      # Uncomment this once frontend tests are implemented
      # - name: Run Frontend Tests
      #   working-directory: ./frontend
      #   run: npm test

  merge-check:
    name: Ensure Merge Success into dev
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history so branches exist

      - name: Fetch all branches
        run: git fetch --all

      - name: Configure Git User (for merging)
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Checkout PR branch
        run: git checkout ${{ github.head_ref }}

      - name: Check Merge Readiness for dev
        run: |
          git checkout dev
          git merge --no-commit --no-ff ${{ github.head_ref }} || exit 1