name: Move Linked Issue to "In Review"

on:
  pull_request:
    types: [linked] # run when PR is linked

jobs:
  move_issue_to_review:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
      contents: read
      project: write
    steps:
      - name: Extract Linked Issue Number
        id: get_issue
        run: |
          ISSUE_NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Get Issue Node ID
        id: get_issue_id
        run: |
          ISSUE_NODE_ID=$(curl -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}" | jq -r .node_id)
          echo "ISSUE_NODE_ID=$ISSUE_NODE_ID" >> $GITHUB_ENV

      - name: Move Issue to "In Review" Column
      # replace YOUR_COLUMN_ID with the project column ID (line 37)
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"content_id": "'"$ISSUE_NODE_ID"'", "content_type": "Issue"}' \
            "https://api.github.com/projects/columns/YOUR_COLUMN_ID/cards"
            
