name: Move Linked Issue to "In Review"

on:
  pull_request:
    types: [opened, synchronize] # Runs when PR is created or updated

jobs:
  move_issue_to_review:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
      contents: read
      projects: write

    steps:
      - name: Extract Linked Issue Number from PR Description
        id: get_issue
        run: |
          ISSUE_NUMBER=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | \
            jq -r '.body' | grep -oE '#[0-9]+' | head -1 | tr -d '#')

          if [ -z "$ISSUE_NUMBER" ]; then
            echo "No linked issue found. Exiting."
            exit 1
          fi

          echo "Found issue #$ISSUE_NUMBER"
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Get Issue Node ID
        id: get_issue_id
        run: |
          ISSUE_NODE_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}" | jq -r .node_id)

          if [ "$ISSUE_NODE_ID" == "null" ]; then
            echo "Failed to get issue node ID"
            exit 1
          fi

          echo "ISSUE_NODE_ID=$ISSUE_NODE_ID" >> $GITHUB_ENV

      - name: Move Issue to "In Review" Column
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"content_id": "'"$ISSUE_NODE_ID"'", "content_type": "Issue"}' \
            "https://api.github.com/projects/columns/PVTSSF_lAHOCIUjhs4Av0rMzgmMOkA/cards"

            - name: Move Issue to "In Review" Column
            run: |
              # Fetch the column ID for "In Review" column
              COLUMN_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/projects/columns" | \
                jq -r '.[] | select(.name == "In Review") | .id')
          
              if [ -z "$COLUMN_ID" ]; then
                echo "Column 'In Review' not found. Exiting."
                exit 1
              fi
          
              # Move the issue to the "In Review" column
              curl -X POST \
                -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                -d '{"content_id": "'"$ISSUE_NODE_ID"'", "content_type": "Issue", "column_id": "'"$COLUMN_ID"'"}' \
                "https://api.github.com/projects/columns/cards"          
